---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/?currentSchema=didaraecm
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: didaraecm

loging:
  level:
    org.springframework.security.oauth2.provider.authentication:
      level: debug

registry:
  url: 172.17.8.141
  port: 8761

server:
  port: 80

oauth:
  server:
#    name: 172.17.8.143
    name: 127.0.0.1
    port: 8090
redis:
  port: 6171
  host: localhost
