#default configuration
registry:
  port: 8761
  #url: 172.17.8.141
  url: 192.168.1.202
oauth:
  server:
#    name: 172.17.8.141
#    port: 8090
#    name: 172.17.8.1
#    port: 80
    name: 192.168.1.202
    port: 8090
---
spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/postgres
    username: postgres
    password: welcome1
---
spring:
  profiles: test
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    name: testdb
    password: testdb
    platform: h2
    initialize: false

---

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  profiles: dev-xnet
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.203:5432/gftc
    username: postgres
    password: welcome1
 
   
logging:
  level:
    org:
      hibernate:
        type: trace


registry:
  port: 8761
  url: 192.168.1.202    

oauth:
  server:
#    name: 172.17.8.141
#    port: 8090
    name: 192.168.1.202
    port: 8090
---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/
    username: postgres
    password: welcome1
registry:
  port: 8761
  url: 172.17.8.141
oauth:
  server:
#    name: 172.17.8.141
    name: localhost
#    port: 8090
    port: 80
