#default configuration
registry:
  port: 8761
  url: 172.17.8.141
oauth:
  server:
#    name: 172.17.8.141
#    port: 8090
    name: 172.17.8.1
    port: 80
---
spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/postgres
    username: postgres
    password: welcome1
---
spring:
  profiles: test
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    name: testdb
    password: testdb
    platform: h2
    initialize: true

---
spring:
  profiles: dev-xnet
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.203:5432/gftc
    username: postgres
    password: welcome1
    
---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/gftc_common
    username: postgres
    password: welcome1
