---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/?currentSchema=ISWC_BAM
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: ISWC_BAM
  
logging:
  level:
    org:
      hibernate:
        type: info
        
oauth:
  server:
    name: localhost
    port: 8090
registry:
  url: 172.17.8.141
  port: 8761
rest:
  resource:
    r0: "rest-measurement-specification-id"
