---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/?currentSchema=oauth
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: oauth
registry-service: 172.17.8.141
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        type: debug
    com:
      didarasoftware:
        security:
          type: debug
---
spring:
  profiles: prod  
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${database_ip:192.168.1.203}:${database_port:5432}/?currentSchema=oauth
    username: ${database_username:postgres}
    password: ${database_password:welcome1}
  properties:
    hibernate:
      default_schema: oauth
---
spring:
  profiles: dev-xnet
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.203:5432/?currentSchema=oauth
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: oauth
registry-service: 192.168.1.202
---
spring:
  profiles: unit-test
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    name: securitydb
    password: securitydb
    platform: h2
