---
spring:
  profiles: dev-xnet
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.203:5432/?currentSchema=ISWC_ROUTES
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: ISWC_ROUTES
      
registry:
  port: 8761
  url: 192.168.1.202   

server:
  port: 80

oauth:
  server:
    name: 192.168.1.202
    port: 8090

gl_code: AIzaSyAeLzulZ4LznK52Z6LRKsddgZM-c5d9RMc
---
spring:
  profiles: dev-iap
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.8.141:5432/?currentSchema=ISWC_ROUTES
    username: postgres
    password: welcome1
  properties:
    hibernate:
      default_schema: ISWC_ROUTES

loging:
  level:
    org.springframework.security.oauth2.provider.authentication:
      level: debug
    org:
      hibernate:
        type: trace
      springframework:
        type: debug                

registry:
  url: 172.17.8.141
  port: 8761

server:
  port: 80

oauth:
  server:
#    name: 172.17.8.143
    name: localhost
    port: 8090
    
gl_code: AIzaSyAeLzulZ4LznK52Z6LRKsddgZM-c5d9RMc
